import type {
  AreaRegistryEntry,
  DeviceRegistryEntry,
  EntityRegistryEntry,
  HomeAssistant,
  LovelaceCardConfig,
  LovelaceDashboardConfig,
  LovelaceViewConfig,
} from "./home-assistant";

const STRATEGY_TYPE = "max-home-dashboard";

interface DashboardStrategyConfig {
  title?: string;
}

interface AreaViewStrategyConfig {
  area: AreaRegistryEntry;
  devices: DeviceRegistryEntry[];
  entities: EntityRegistryEntry[];
}

export class MaxHomeDashboardStrategy extends HTMLElement {
  static getCreateSuggestions(_hass: HomeAssistant): { title: string; icon: string } {
    return {
      title: "Max Home",
      icon: "mdi:home-assistant",
    };
  }

  static async generate(
    config: DashboardStrategyConfig,
    hass: HomeAssistant,
  ): Promise<LovelaceDashboardConfig> {
    const [areas, devices, entities] = await Promise.all([
      hass.callWS<AreaRegistryEntry[]>({ type: "config/area_registry/list" }),
      hass.callWS<DeviceRegistryEntry[]>({ type: "config/device_registry/list" }),
      hass.callWS<EntityRegistryEntry[]>({ type: "config/entity_registry/list" }),
    ]);

    const visibleAreas = areas
      .filter((area) => area.area_id && area.name)
      .sort((left, right) => left.name.localeCompare(right.name));

    return {
      title: config.title ?? "Max Home",
      views: [
        createOverviewView(hass, visibleAreas),
        ...visibleAreas.map((area) => ({
          title: area.name,
          path: slugify(area.name || area.area_id),
          icon: area.icon ?? undefined,
          strategy: {
            type: `custom:${STRATEGY_TYPE}`,
            area,
            devices,
            entities,
          },
        })),
      ],
    };
  }
}

export class MaxHomeAreaViewStrategy extends HTMLElement {
  static async generate(
    config: AreaViewStrategyConfig,
    hass: HomeAssistant,
  ): Promise<Pick<LovelaceViewConfig, "cards">> {
    const entityIds = getEntitiesForArea(config)
      .filter((entityId) => hass.states[entityId])
      .sort((left, right) => friendlyName(hass, left).localeCompare(friendlyName(hass, right)));

    return {
      cards: buildAreaCards(config.area, entityIds),
    };
  }
}

function createOverviewView(hass: HomeAssistant, areas: AreaRegistryEntry[]): LovelaceViewConfig {
  const locationName = hass.config.location_name ?? "Home";

  return {
    title: "Overview",
    path: "overview",
    icon: "mdi:view-dashboard",
    cards: [
      {
        type: "markdown",
        content: `# ${locationName}\n\nGenerated by the Max Home dashboard strategy.`,
      },
      {
        type: "grid",
        columns: 2,
        square: false,
        cards: areas.map((area) => ({
          type: "button",
          name: area.name,
          icon: area.icon ?? "mdi:floor-plan",
          tap_action: {
            action: "navigate",
            navigation_path: `/${slugify(area.name || area.area_id)}`,
          },
        })),
      },
    ],
  };
}

function buildAreaCards(area: AreaRegistryEntry, entityIds: string[]): LovelaceCardConfig[] {
  if (entityIds.length === 0) {
    return [
      {
        type: "markdown",
        content: `## ${area.name}\n\nNo visible entities are assigned to this area yet.`,
      },
    ];
  }

  return [
    {
      type: "entities",
      title: area.name,
      entities: entityIds,
    },
  ];
}

function getEntitiesForArea(config: AreaViewStrategyConfig): string[] {
  const areaDeviceIds = new Set(
    config.devices.filter((device) => device.area_id === config.area.area_id).map((device) => device.id),
  );

  return config.entities
    .filter((entity) => !entity.hidden_by && !entity.disabled_by)
    .filter(
      (entity) =>
        entity.area_id === config.area.area_id ||
        (!entity.area_id && entity.device_id !== null && entity.device_id !== undefined && areaDeviceIds.has(entity.device_id)),
    )
    .map((entity) => entity.entity_id);
}

function friendlyName(hass: HomeAssistant, entityId: string): string {
  return hass.states[entityId]?.attributes.friendly_name ?? entityId;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function registerStrategies(): void {
  customElements.define(`ll-strategy-dashboard-${STRATEGY_TYPE}`, MaxHomeDashboardStrategy);
  customElements.define(`ll-strategy-view-${STRATEGY_TYPE}`, MaxHomeAreaViewStrategy);

  window.customStrategies = window.customStrategies || [];
  window.customStrategies.push({
    type: STRATEGY_TYPE,
    strategyType: "dashboard",
    name: "Max Home",
    description: "Generates an area-based Home Assistant dashboard.",
    documentationURL: "https://developers.home-assistant.io/docs/frontend/custom-ui/custom-strategy/",
  });
}

declare global {
  interface Window {
    customStrategies?: Array<{
      type: string;
      strategyType: "dashboard" | "view";
      name?: string;
      description?: string;
      documentationURL?: string;
    }>;
  }
}
